create table AML_WARN_RECEIPT(
REC_ID VARCHAR(32) NOT NULL,
FILENAME  VARCHAR(200),
IMPORT_TIME VARCHAR(14),
IMPORT_TLR  VARCHAR(20),
RSV1 VARCHAR(20),
RSV2 VARCHAR(50),
RSV3 VARCHAR(100)
);


insert into FUNCTION_INFO (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, EFFECT_DATE, EXPIRE_DATE, TIMESTAMPS, MISCFLGS, MISC, ICON_CLS) values ('90_303', '警告回执导入_3', '/fpages/hfaml3/ftl/AMLReceiptFdacImport.ftl', 2, 0, '90_3', 3, null, '1', null, null, null, '1', null, null, null, null, null, 'icon-impin');

insert into SYS_PARAMS (PARAMGROUP_ID, PARAM_ID, PARAM_VAL, PARAM_NAME, MEMO, ST, IS_LOCK, IS_DEL, CRT_DT, LAST_UPD_TMS, LAST_UPD_OPER) values ('FEEDBACK', 'WARN', '/appvol/file/receipt/warn/', 'AML警告回执文件的路径', '该目录的子目录是日期yyyyMMdd', '4', 'F', 'F', '20120917', '20120917101519', null);
